#define BLACK_PLATFORM_WINDOWS
/* #undef BLACK_PLATFORM_LINUX */
/* #undef BLACK_PLATFORM_MACOSX */
#define BLACK_PLATFORM "Windows"

/* #undef BLACK_COMPILER_CLANG */
#define BLACK_COMPILER_MINGW
/* #undef BLACK_COMPILER_GNU */
/* #undef BLACK_COMPILER_INTEL */
/* #undef BLACK_COMPILER_MSVC */
